### ISSUE TITLE
Log to file?

### ISSUE THREAD

**Issue by kev-mas** [remko/smtp-http-proxy#8]
Hello,

I'm running this proxy in K8S and noticed it only logs to StandardOut. Is there way to log to file too?

Thanks!

**Comment by remko** [comment]
It actually logs to standard error.

If you containerize it, you could tee/redirect it to a file from within your starting script. Or if you don't use a supervisor, use `CMD ["/bin/sh", "-c", "/opt/src/smtp-http-proxy 2> server.log"]` or such?

Or in managed k8s settings, just let it go to standard out, and use k8s logging infrastructure handle it?

**Comment by kev-mas** [comment]
> It actually logs to standard error.
> 
> If you containerize it, you could tee/redirect it to a file from within your starting script. Or if you don't use a supervisor, use `CMD ["/bin/sh", "-c", "/opt/src/smtp-http-proxy 2> server.log"]` or such?
> 
> Or in managed k8s settings, just let it go to standard out, and use k8s logging infrastructure handle it?

Thanks! Will try using `tee` :D

**Comment by kev-mas** [comment]
Hey @remko 

We got it to work to log into a log file and to Standard Error using the following:

```
/usr/bin/smtp-http-proxy --bind 0.0.0.0 --port 25 --debug --url $HTTPURL 2>&1 | tee -a /var/log/smtp-http-proxy.log
```

Thanks!
