### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by RestOp** [remko/smtp-http-proxy#9]
Hello,

after  apt-get update i get 
Ign:1 http://cdn.el-tramo.be debian/smtp-http-proxy/ InRelease
Err:2 http://cdn.el-tramo.be debian/smtp-http-proxy/ Release
  404  Not Found [IP: 52.28.4.5 80]

an after apt-get install smtp-http-proxy

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package smtp-http-proxy

**Comment by remko** [comment]
This now needs to be 

    deb [allow-insecure=yes] http://cdn.el-tramo.be debian/smtp-http-proxy/

but the packages don't work on newer Debians anyway. I need to rebuild them for the latest stable.

**Comment by remko** [comment]
Repo should now be fixed.

**Comment by RestOp** [comment]
Thanks a lot!
Sorry, i am not good in linux(((
A am running Raspberry Pi4 with Openhabian.

After i changed the source i get

`apt-get update
E: Conflicting values set for option ALLOW_INSECURE regarding source <set> <unset>
E: The list of sources could not be read.`

Could it be fixed?

PS
I have added this source to separate file http://prntscr.com/py2vs6
